name: Deploy Java Tomcat Stack

on:
  push:
    paths:
      - 'java-app/**'
      - '.github/workflows/deploy-java.yml'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Java 17 Runtime
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Compile and Package with Maven
      run: |
        cd java-app
        mvn clean package

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

   - name: Deploy War Artifact to Target Tomcat S3 Bucket
      run: |
        echo "Uploading ROOT.war to S3 deployment bucket..."
        aws s3 cp java-app/target/ROOT.war s3://dev-java-app-deploy-bucket-674693859537/ROOT.war

    - name: Trigger Auto Scaling Instance Refresh
      run: |
        echo "Refreshing Auto Scaling Group to pull down the new code..."
        aws autoscaling start-instance-refresh --auto-scaling-group-name java-tomcat-asg